language: python
python:
  - "3.6.3"

# command to install dependencies
install:
  - pip install codecov

script:
  - coverage run TEST1.py

after_success:
  - codecovst # or py.test for Python versions 3.5 and below